"""Add Operation

Revision ID: 11de36c0e8b5
Revises: fe31c875ebb6
Create Date: 2024-07-05 20:25:41.527499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11de36c0e8b5'
down_revision: Union[str, None] = 'fe31c875ebb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
